version: '3.7'

services:
  postgres:
    container_name: aikamsoft-postgres
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aikamsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  default:
    name: test-network
    driver: bridge